### PR TITLE
conf: Use non-GPU laser plugin

### PR DESCRIPTION
**Pull request by luator**
## What I Did
Use non-GPU laser plugin.

The non-GPU based laser plugin has a somewhat worse performance than its
GPU-based counterpart but our Jenkins server does not have a GPU so we
are not able to run simulation tests with the GPU plugin.

This should fix current problem discussed in synapticon/CP1500101_RoboYagi/pull/1289.

## How I Tested
Running simulation on my laptop.

### CODE REVIEW

**Comment by thiagodefreitas** [comment]
@luator as far as I remember this affects only the visualization of the **scans** right? I mean, the measurements are not severely degraded

**Comment by luator** [comment]
@thiagodefreitas I did not verify but assuming that rviz visualises correctly, the measurements *are* degraded. I don't yet understand why this is the case, maybe it is possible to fix it somehow.

**Comment by thiagodefreitas** [comment]
yeah, I can not test it now, but after a second, I remember that they are indeed degraded. I am fine with the content of the PR, as for the issue we are currently facing, but I would create an issue to keep a track of this anyway

**Comment by luator** [comment]
@thiagodefreitas Do you have permission to enable issues on this repo?

**Comment by thiagodefreitas** [comment]
@luator I had and it is done. I have also added the lona-team as admin

**Comment by luator** [comment]
See #2

**Pull request merged**
